### ISSUE TITLE
Solved.dat not updating correctly.

### ISSUE THREAD

**Issue by HazelTheOrphanSlayer** [mochimodev/mochimo#31]
In cases where nodes win the orphan battle and possibly in non-orphan cases, blocks solve and the reward is paid, but the solvedl.dat does not advance.  One possible solution is to delete the solved.dat from \d but that extinguishes valuable data on the total blocks solved.

**Comment by chrisdigity** [comment]
If that solution fixes the problem for the people it affects, one possible fix might be to delete the existing file before writing the value to a brand new one instead of simply overwriting the files contents.

I am still unsure on the cause of the issue.

**Comment by mochimodev** [comment]
Please repost this issue to the Windows Miner repository - it does not affect the main line full node code.

**Comment by chrisdigity** [comment]
This issue does infact relate to the full node code, however I cannot replicate the issue consistently and suspect a system type issue rather than a code issue.
Tests for a fix have been attempted but showed no success.
A suggestion in another issue where the miner checks the mining address for balance instead of recording blocks solved would be a welcome solution
