### ISSUE TITLE
do not change difficule every block

### ISSUE THREAD

**Issue by iDagger** [mochimodev/mochimo#48]
change difficult every block will cause block slove time become not stable, such as 48 6min, 49  12min  ,50 24min, It case tx time change very fast.when I want to send balance to others, It always will wait for long time until 50 difficult slove, because  difficule 48 sloved very fast.

**Comment by iDagger** [comment]
presu*** block will take 15 min, it take long

**Comment by chrisdigity** [comment]
Thanks iDagger, Devs are actively fixing this issue. In fact, V2.3 of the codebase, which is under open-beta testing in our discord as we speak, will not only stabilise the block times on the network but also resist extended periods of long block times due to massive amounts of hash power dropping off the network.

**Comment by Stoner19** [comment]
The difficulty adjustment every block is designed to be much more efficient for the miners. I've seen so many altcoins that have a difficulty based similarly to that of Bitcoin where it only adjusts after several hundred blocks, or more, where a miner brings a significant amount of hash to the chain, drives up the difficulty, and then removes their hash. This results in a chain that is nearly impossible to mine due to the high difficulty and low hash rate. Sometimes this is malicious, other times not, but regardless, changing the difficulty every block seems to be a strong mechanism to protecting the stability of the chain itself as net hash fluctuates.

**Comment by iDagger** [comment]
i dont think so,  we need tx solve smoothly, when I send some mcm to others, i dont want to wait so long, with fast diff change algo ,  when the time i send to other,it have high change between the high diff block time ,i need wait for long.with slow change diff algo, my tx time always a average time

**Comment by iDagger** [comment]
i think v2.3 did not slove the problem of tx time too long, but the longest time is about 949 minites, i think its ok

**Comment by Stoner19** [comment]
v2.3 is still a work in progress and a lot of things still being resolved. I'm sure this is something that will be corrected on testnet before it's ported over to mainnet.

**Comment by chrisdigity** [comment]
The transition to v2.3 has come and gone. Mochimap has now been reporting an average block time of a little over 5 minutes ever since the switch to v2.3. On top of that, we are seeing an average of around 256 "reward blocks" in a day, matching the original targets of the blockchain.
Yes, there will be a few pseudoblocks produced pushing transaction times past 15 minutes on some occasions. These few extended transaction times are a small price to pay for a network capable of recovering from either speculative miner abuse, a massive loss of hashing power or lucky solves which drive the network difficulty too high.

All things considered, I believe @mochimodev can close this issue out now...

**Comment by mochimodev** [comment]
Closing on recommendation of chrisdigity, and I agree - block times are working perfectly since v2.3.
